name = "tanstack-start-ts"
main = "dist/server/index.mjs"
compatibility_date = "2026-06-08"
compatibility_flags = ["nodejs_compat"]
no_bundle = true

[[rules]]
type = "ESModule"
globs = ["**/*.mjs", "**/*.js"]

[assets]
directory = "dist/client"
binding = "ASSETS"
